name: test runner workflow
on: workflow_dispatch
jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
          - name: checkout
            uses: actions/checkout@v4
          - name: setup-java
            uses: actions/setup-java@v4
            with:
                distribution: jetbrains
                java-version: '21'