name: test runner workflow
on:
  push:
    branches:
        - main
jobs:
  test:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: setup jdk
          uses: actions/setup-java@v4
          with:
            distribution: jetbrains
            java-version: '21'
        - name: cache maven dependencies
          uses: actions/cache@v4
          with:
            path: ~/.m2
            key: ${{ runner.os }}-maven-$${{ hashFiles('**/pom.xml') }}
            restore-keys: ${{ runner.os }}-maven-
        - name: install dependencies
          run: mvn install -DskipTests
        - name: run tests
          run: mvn test